import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";

const activity = [
 { d:"12 Sep", volume:42, success:36, risk:4 }, { d:"13 Sep", volume:56, success:47, risk:6 }, { d:"14 Sep", volume:49, success:44, risk:3 }, { d:"15 Sep", volume:71, success:62, risk:7 }, { d:"16 Sep", volume:65, success:58, risk:4 }, { d:"17 Sep", volume:88, success:79, risk:5 }, { d:"18 Sep", volume:76, success:68, risk:3 },
];
const trend = [{d:"Apr",v:3},{d:"May",v:4},{d:"Jun",v:3},{d:"Jul",v:5},{d:"Aug",v:11},{d:"Sep",v:18}];

const tooltipStyle = { background:"var(--popover)", border:"1px solid var(--border)", borderRadius:8, fontSize:11, color:"var(--foreground)" };

export function PaymentActivityChart() { return <div className="h-64 w-full"><ResponsiveContainer width="100%" height="100%"><AreaChart data={activity} margin={{top:10,right:8,left:-25,bottom:0}}><defs><linearGradient id="vol" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="var(--chart-volume)" stopOpacity={.28}/><stop offset="100%" stopColor="var(--chart-volume)" stopOpacity={0}/></linearGradient></defs><CartesianGrid vertical={false} stroke="var(--border)" strokeDasharray="3 3"/><XAxis dataKey="d" axisLine={false} tickLine={false} tick={{fill:"var(--muted-foreground)",fontSize:10}}/><YAxis axisLine={false} tickLine={false} tick={{fill:"var(--muted-foreground)",fontSize:10}}/><Tooltip contentStyle={tooltipStyle}/><Area type="monotone" dataKey="volume" stroke="var(--chart-volume)" strokeWidth={2} fill="url(#vol)"/><Area type="monotone" dataKey="success" stroke="var(--risk-low)" strokeWidth={1.5} fill="transparent"/><Area type="monotone" dataKey="risk" stroke="var(--risk-high)" strokeWidth={1.5} fill="transparent"/></AreaChart></ResponsiveContainer></div>; }

export function RiskDistribution() { const data=[{name:"High",value:3,c:"var(--risk-high)"},{name:"Medium",value:7,c:"var(--risk-medium)"},{name:"Low",value:24,c:"var(--risk-low)"}]; return <div className="grid grid-cols-[1fr_1fr] items-center gap-2 px-5 pb-5"><div className="relative h-44"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={data} dataKey="value" innerRadius={52} outerRadius={70} paddingAngle={3} stroke="none">{data.map(x=><Cell key={x.name} fill={x.c}/>)}</Pie><Tooltip contentStyle={tooltipStyle}/></PieChart></ResponsiveContainer><div className="pointer-events-none absolute inset-0 grid place-items-center text-center"><div><p className="text-2xl font-semibold">34</p><p className="text-[9px] uppercase tracking-widest text-muted-foreground">Analyzed</p></div></div></div><div className="space-y-3">{data.map(x=><div key={x.name} className="flex items-center justify-between"><span className="flex items-center gap-2 text-xs text-muted-foreground"><span className="size-2 rounded-full" style={{background:x.c}}/>{x.name}</span><span className="font-mono text-sm">{x.value}</span></div>)}</div></div>; }

export function MiniTrendChart({ kind="line" }: {kind?:"line"|"bar"}) { return <div className="h-36"><ResponsiveContainer width="100%" height="100%">{kind==="bar"?<BarChart data={trend}><CartesianGrid vertical={false} stroke="var(--border)"/><XAxis dataKey="d" axisLine={false} tickLine={false} tick={{fill:"var(--muted-foreground)",fontSize:9}}/><Tooltip contentStyle={tooltipStyle}/><Bar dataKey="v" fill="var(--chart-volume)" radius={[3,3,0,0]}/></BarChart>:<AreaChart data={trend}><defs><linearGradient id="trend" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="var(--chart-volume)" stopOpacity={.25}/><stop offset="1" stopColor="var(--chart-volume)" stopOpacity={0}/></linearGradient></defs><CartesianGrid vertical={false} stroke="var(--border)"/><XAxis dataKey="d" axisLine={false} tickLine={false} tick={{fill:"var(--muted-foreground)",fontSize:9}}/><Tooltip contentStyle={tooltipStyle}/><Area dataKey="v" type="monotone" stroke="var(--chart-volume)" fill="url(#trend)" strokeWidth={2}/></AreaChart>}</ResponsiveContainer></div>; }
