import { useMemo, useState } from "react";
import { Link } from "@tanstack/react-router";
import { CalendarDays, ChevronDown, Filter, Lightbulb, Search, Settings2, ShieldAlert, Sparkles } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { AppShell, NewPaymentButton, PageIntro } from "./app-shell";
import { InsightCard, Panel, payments, PaymentTable, RiskBadge, SectionHead, StatusBadge } from "./shared";
import { MiniTrendChart, PaymentActivityChart } from "./charts";

export function PaymentsPage(){const [q,setQ]=useState("");const rows=useMemo(()=>payments.filter(p=>p.vendor.toLowerCase().includes(q.toLowerCase())||p.id.toLowerCase().includes(q.toLowerCase())),[q]);return <AppShell title="Payments"><PageIntro title="Payments" description="Review every payment across your business." action={<NewPaymentButton/>}/><Panel><div className="grid gap-3 border-b border-border p-4 md:grid-cols-[minmax(220px,1fr)_repeat(4,auto)]"><div className="relative"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground"/><Input value={q} onChange={e=>setQ(e.target.value)} className="pl-9" placeholder="Search payments..."/></div>{["Date","Currency","Risk","Status"].map(x=><Button key={x} variant="outline" className="justify-between">{x}<ChevronDown/></Button>)}</div>{rows.length?<PaymentTable rows={rows}/>:<div className="py-14 text-center text-sm text-muted-foreground">No payments match your search.</div>}</Panel></AppShell>}

export function RiskCenterPage(){const [filter,setFilter]=useState("All");const rows=filter==="All"?payments:filter==="Needs Review"?payments.filter(p=>p.status.includes("Review")):payments.filter(p=>p.risk===filter.toUpperCase());return <AppShell title="Risk Center"><PageIntro title="Risk Center" description="Investigate payment signals and resolve items needing review."/><Panel><div className="grid gap-3 border-b border-border p-4 lg:grid-cols-[minmax(220px,1fr)_auto]"><div className="relative max-w-md"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground"/><Input className="pl-9" placeholder="Search risk alerts..."/></div><div className="flex gap-1 overflow-x-auto rounded-lg bg-secondary p-1">{["All","High","Medium","Low","Needs Review"].map(x=><button key={x} onClick={()=>setFilter(x)} className={`whitespace-nowrap rounded-md px-3 py-1.5 text-xs ${filter===x?"bg-card text-foreground shadow-sm":"text-muted-foreground"}`}>{x}</button>)}</div></div><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left"><thead><tr className="border-b border-border text-[10px] uppercase tracking-widest text-muted-foreground"><th className="px-5 py-3">Vendor</th><th className="px-5 py-3">Payment</th><th className="px-5 py-3">Risk</th><th className="px-5 py-3">Signals</th><th className="px-5 py-3">Status</th><th className="px-5 py-3">Action</th></tr></thead><tbody>{rows.map(p=><tr key={p.id} className="border-b border-border last:border-0 hover:bg-accent/30"><td className="px-5 py-4 text-sm font-medium">{p.vendor}</td><td className="px-5 py-4 text-sm tabular-nums">{p.amount}</td><td className="px-5 py-4"><RiskBadge risk={p.risk}/></td><td className="px-5 py-4 text-xs text-muted-foreground">{p.risk==="HIGH"?"3 anomalies":p.risk==="MEDIUM"?"1 anomaly":"No anomalies"}</td><td className="px-5 py-4"><StatusBadge status={p.status}/></td><td className="px-5 py-4"><Button variant="outline" size="sm" asChild><Link to="/risk-review">Review</Link></Button></td></tr>)}</tbody></table></div></Panel></AppShell>}

export function InsightsPage(){return <AppShell title="Payment Insights"><PageIntro title="Payment Insights" description="Understand risk, cost and payment behavior across your business."/><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[["Risk Trends","18","events this quarter"],["Payment Volume","₹1.84Cr","processed this month"],["Avg. Transaction Cost","₹812","down 8.4%"],["Route Reliability","96.2%","across all providers"]].map(([l,v,d])=><Panel key={l} className="p-5"><p className="text-xs text-muted-foreground">{l}</p><p className="mt-3 text-2xl font-semibold tabular-nums">{v}</p><p className="mt-1 text-[10px] text-muted-foreground">{d}</p></Panel>)}</div><div className="mt-5 grid gap-5 xl:grid-cols-2"><Panel><SectionHead title="Risk Events Over Time" detail="Recurring vendor anomalies and severity"/><div className="p-5"><MiniTrendChart/></div></Panel><Panel><SectionHead title="Payment Volume" detail="Monthly analyzed transactions"/><div className="p-5"><MiniTrendChart kind="bar"/></div></Panel><Panel><SectionHead title="Route Performance" detail="Reliability by payment rail"/><div className="space-y-4 p-5">{[["Provider C","97%"],["Bank Transfer","94%"],["Provider B","91%"]].map(([l,v],i)=><div key={l}><div className="mb-2 flex justify-between text-xs"><span>{l}</span><span className="font-mono">{v}</span></div><div className="h-1.5 rounded-full bg-secondary"><div className="h-full rounded-full bg-primary" style={{width:v}}/></div></div>)}</div></Panel><Panel><SectionHead title="Recurring Anomalies" detail="Signals detected across vendors"/><div className="divide-y divide-border px-5">{[["Unusual amount","8 detections"],["New destination","5 detections"],["Unusual timing","5 detections"]].map(([l,v])=><div key={l} className="flex justify-between py-4 text-sm"><span>{l}</span><span className="text-muted-foreground">{v}</span></div>)}</div></Panel></div><div className="mt-5 grid gap-5 md:grid-cols-2"><InsightCard label="AI Insight" link="View Vendor">ABC Software has shown a significant increase in payment amounts over the last three transactions.</InsightCard><InsightCard label="Cost Insight" link="Compare Routes">Route C has provided better reliability for similar USD payments while keeping settlement costs balanced.</InsightCard></div></AppShell>}

export function SimplePage({kind}:{kind:"settings"|"help"}){return <AppShell title={kind==="settings"?"Settings":"Help Center"}><PageIntro title={kind==="settings"?"Settings":"Help Center"} description={kind==="settings"?"Manage business preferences and payment controls.":"Get support for payment analysis and FinSight workflows."}/><Panel className="p-6"><div className="flex items-start gap-4"><span className="grid size-10 place-items-center rounded-md bg-primary/10 text-primary">{kind==="settings"?<Settings2 className="size-5"/>:<Lightbulb className="size-5"/>}</span><div><h3 className="font-medium">{kind==="settings"?"Business controls":"FinSight support"}</h3><p className="mt-1 text-sm text-muted-foreground">{kind==="settings"?"Configure approval thresholds, review rules, and notification preferences.":"Browse guidance for risk reviews, route selection, and payment monitoring."}</p></div></div></Panel></AppShell>}
