import { useEffect, useState } from "react";
import { Link, useNavigate } from "@tanstack/react-router";
import { AlertTriangle, ArrowRight, Building2, Check, CheckCircle2, ChevronDown, Circle, Clock3, FileCheck2, FileText, Landmark, Pencil, Route as RouteIcon, ShieldCheck, Sparkles, UploadCloud } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Input } from "@/components/ui/input";
import { AppShell, PageIntro } from "./app-shell";
import { DemoLabel, Panel, RiskBadge, SectionHead } from "./shared";
import { MiniTrendChart } from "./charts";
import { cn } from "@/lib/utils";

const details=[ ["Vendor","ABC Software LLC"], ["Amount","$18,700"], ["Currency","USD"], ["Destination","United States"], ["Due Date","18 September 2026"], ["Payment Account","•••• 9137"], ["Invoice Number","INV-1048"] ];

export function NewPaymentPage() { const [stage,setStage]=useState<"upload"|"analyzing"|"details">("upload"); useEffect(()=>{if(stage==="analyzing"){const t=setTimeout(()=>setStage("details"),1800);return()=>clearTimeout(t)} return undefined},[stage]); return <AppShell title="New Payment" eyebrow="Payments / New"><PageIntro title="Create New Payment" description="Analyze a payment before money moves."/><div className="mx-auto max-w-4xl">
 {stage==="upload"&&<><Panel className="border-dashed p-6 sm:p-10"><div className="group flex min-h-72 w-full flex-col items-center justify-center rounded-lg border border-dashed border-border bg-secondary/25 p-8 transition-colors hover:border-primary/50 hover:bg-primary/5"><span className="grid size-14 place-items-center rounded-xl border border-primary/20 bg-primary/10 text-primary"><UploadCloud className="size-6"/></span><h3 className="mt-5 text-lg font-semibold">Upload Invoice</h3><p className="mt-2 text-sm text-muted-foreground">Drag & drop your invoice here</p><p className="mt-1 text-[10px] uppercase tracking-widest text-muted-foreground">PDF, PNG, JPG · Max 10MB</p><Button className="mt-6" type="button" onClick={()=>setStage("analyzing")}>Choose File</Button></div></Panel><div className="my-5 flex items-center gap-4 text-[10px] uppercase tracking-widest text-muted-foreground"><span className="h-px flex-1 bg-border"/>or<span className="h-px flex-1 bg-border"/></div><Button variant="outline" className="w-full">Enter Manually</Button></>}
 {stage==="analyzing"&&<Panel className="min-h-[420px] p-8"><div className="mx-auto flex max-w-lg flex-col items-center pt-16 text-center"><div className="relative grid size-20 place-items-center rounded-full border border-primary/30 bg-primary/5"><span className="absolute inset-0 animate-ping rounded-full border border-primary/20"/><Sparkles className="size-7 animate-pulse text-primary"/></div><h3 className="mt-7 text-lg font-semibold">Analyzing document...</h3><p className="mt-2 text-sm text-muted-foreground">FinSight is extracting payment fields and checking document signals.</p><div className="mt-8 h-1.5 w-full overflow-hidden rounded-full bg-secondary"><div className="h-full w-4/5 animate-progress rounded-full bg-primary"/></div><div className="mt-4 flex w-full justify-between text-[10px] text-muted-foreground"><span>Invoice fields</span><span>Vendor identity</span><span>Payment data</span></div></div></Panel>}
 {stage==="details"&&<Panel><SectionHead title="Extracted Payment Details" detail="Review the information before analysis" action={<span className="flex items-center gap-1.5 text-xs text-risk-low"><FileCheck2 className="size-4"/> Extraction complete</span>}/><div className="grid gap-4 p-5 sm:grid-cols-2">{details.map(([l,v])=><label key={l} className="block"><span className="mb-1.5 block text-xs text-muted-foreground">{l}</span><div className="relative"><Input defaultValue={v} className="h-11 bg-secondary/35 pr-9"/><Pencil className="absolute right-3 top-3.5 size-3.5 text-muted-foreground"/></div></label>)}</div><div className="flex justify-end border-t border-border p-5"><Button asChild><Link to="/risk-review">Analyze Payment <ArrowRight/></Link></Button></div></Panel>}
 </div></AppShell>; }

const factors=[
 {title:"New destination account",severity:"HIGH",icon:Landmark,prev:"Previous: •••• 4821",curr:"Current: •••• 9137",desc:"This account has not appeared in 14 prior payments to this vendor."},
 {title:"Unusual payment amount",severity:"HIGH",icon:AlertTriangle,prev:"Historical: $2,000–$5,000",curr:"Current: $18,700",desc:"The requested amount is 3.7× above the highest recorded payment."},
 {title:"Unusual timing",severity:"MEDIUM",icon:Clock3,prev:"Typical: Monthly",curr:"Current: Urgent / early",desc:"The request arrived 11 days earlier than the established monthly schedule."},
];
export function RiskReviewPage() { const [open,setOpen]=useState(0); return <AppShell title="Payment Risk Review" eyebrow="Payments / PAY-1048"><PageIntro title="Payment Risk Review" description="ABC Software LLC  ·  $18,700 USD" action={<RiskBadge risk="HIGH"/>}/>
 <div className="grid gap-5 xl:grid-cols-[minmax(0,1.45fr)_minmax(330px,.65fr)]"><div className="space-y-5"><Panel className="overflow-hidden"><div className="grid items-center gap-8 p-6 sm:grid-cols-[220px_1fr] sm:p-8"><div className="relative mx-auto grid size-44 place-items-center rounded-full risk-ring"><div className="grid size-36 place-items-center rounded-full bg-card text-center"><div><p className="text-[10px] font-semibold uppercase tracking-[.18em] text-muted-foreground">Payment risk</p><p className="mt-1 text-4xl font-semibold tabular-nums">82<span className="text-base text-muted-foreground"> / 100</span></p><p className="mt-2 text-xs font-semibold text-risk-high">HIGH RISK</p></div></div></div><div><p className="text-[10px] font-semibold uppercase tracking-[.16em] text-risk-high">Review required</p><h3 className="mt-3 text-xl font-semibold">FinSight detected 3 significant anomalies.</h3><p className="mt-3 max-w-xl text-sm leading-6 text-muted-foreground">This payment departs materially from the vendor's established behavioral profile. Verify the evidence below before selecting a route.</p><div className="mt-6 flex gap-5 text-xs"><span><b className="mr-1 text-foreground">14</b><span className="text-muted-foreground">payments analyzed</span></span><span><b className="mr-1 text-foreground">18 mo</b><span className="text-muted-foreground">history</span></span></div></div></div></Panel>
 <Panel><SectionHead title="Risk Factors" detail="Evidence contributing to this assessment"/><div>{factors.map((f,i)=>{const Icon=f.icon;return <button key={f.title} className="w-full border-b border-border text-left last:border-0" onClick={()=>setOpen(open===i?-1:i)}><div className="grid grid-cols-[auto_minmax(0,1fr)_auto] items-center gap-3 p-4 sm:p-5"><span className={cn("grid size-9 place-items-center rounded-md",f.severity==="HIGH"?"bg-risk-high/10 text-risk-high":"bg-risk-medium/10 text-risk-medium")}><Icon className="size-4"/></span><span className="min-w-0"><span className="block text-sm font-medium">{f.title}</span><span className="mt-1 block text-xs text-muted-foreground"><span className="line-through opacity-70">{f.prev}</span><span className="mx-2">→</span><span className="text-foreground">{f.curr}</span></span></span><ChevronDown className={cn("size-4 text-muted-foreground transition-transform",open===i&&"rotate-180")}/></div>{open===i&&<p className="animate-fade-in px-5 pb-5 pl-16 text-xs leading-5 text-muted-foreground">{f.desc}</p>}</button>})}</div></Panel>
 <WhatChanged/></div><div className="space-y-5"><PaymentDNA/><Panel className="border-primary/20"><SectionHead title="Why FinSight Flagged This" detail="AI reasoning based on payment history" action={<Sparkles className="size-4 text-primary"/>}/><div className="p-5"><p className="text-sm leading-6 text-foreground/90">The payment differs from the vendor's historical pattern in three important ways. The destination account is new, the amount is significantly above the usual range, and the timing is unusual.</p><div className="mt-5 rounded-md border border-risk-high/20 bg-risk-high/5 p-4"><p className="text-[10px] uppercase tracking-widest text-muted-foreground">Recommended Action</p><p className="mt-1 text-sm font-semibold text-risk-high">PAUSE & VERIFY</p></div><div className="mt-5 grid gap-2 sm:grid-cols-2 xl:grid-cols-1"><Button variant="outline"><ShieldCheck/>Verify Vendor</Button><Button asChild><Link to="/route-intelligence">Continue to Route Analysis<ArrowRight/></Link></Button></div></div></Panel></div></div>
 </AppShell>; }

function WhatChanged(){return <Panel><SectionHead title="What Changed?" detail="Historical behavior compared with this request" action={<span className="text-xs font-medium text-risk-high">3 changes detected</span>}/><div className="grid md:grid-cols-2"><div className="border-b border-border p-5 md:border-b-0 md:border-r"><p className="mb-4 text-[10px] font-semibold uppercase tracking-[.15em] text-muted-foreground">Historical</p>{[["Account","•••• 4821"],["Typical amount","$2K–$5K"],["Frequency","Monthly"]].map(x=><div key={x[0]} className="flex justify-between border-t border-border py-3 text-sm"><span className="text-muted-foreground">{x[0]}</span><span className="font-mono">{x[1]}</span></div>)}</div><div className="bg-risk-high/[.025] p-5"><p className="mb-4 text-[10px] font-semibold uppercase tracking-[.15em] text-risk-high">Current</p>{[["Account","•••• 9137"],["Amount","$18,700"],["Timing","Urgent"]].map(x=><div key={x[0]} className="flex justify-between border-t border-risk-high/15 py-3 text-sm"><span className="text-muted-foreground">{x[0]}</span><span className="font-mono font-medium text-risk-high">{x[1]}</span></div>)}</div></div></Panel>}
function PaymentDNA(){return <Panel><SectionHead title="Payment DNA" detail="Behavioral profile based on historical payment activity"/><div className="grid grid-cols-2 gap-px bg-border"><DnaStat l="Typical Amount" v="$2K–$5K"/><DnaStat l="Currency" v="USD"/><DnaStat l="Frequency" v="Monthly"/><DnaStat l="Destinations" v="1"/><DnaStat l="Payment Day" v="15th"/><DnaStat l="History" v="14 payments"/></div><div className="p-5"><p className="mb-3 text-[10px] uppercase tracking-widest text-muted-foreground">Historical amount trend</p><MiniTrendChart/></div></Panel>}
function DnaStat({l,v}:{l:string;v:string}){return <div className="bg-card p-4"><p className="text-[10px] text-muted-foreground">{l}</p><p className="mt-1 text-sm font-medium tabular-nums">{v}</p></div>}
