import { useEffect, useState } from "react";
import { Link } from "@tanstack/react-router";
import { AlertTriangle, ArrowRight, Check, CheckCircle2, Circle, Clock3, IndianRupee, Landmark, RefreshCw, Route as RouteIcon, ShieldCheck, Sparkles, Zap } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { AppShell, PageIntro } from "./app-shell";
import { DemoLabel, Panel, RiskBadge, SectionHead, StatusBadge } from "./shared";
import { cn } from "@/lib/utils";

const routes=[
 {id:"A",name:"Bank Transfer",provider:"Direct bank network",cost:"₹1,420",settlement:"2–3 days",reliability:"94%",risk:"LOW" as const,icon:Landmark},
 {id:"B",name:"Provider B",provider:"Real-time payment rail",cost:"₹680",settlement:"10 min",reliability:"91%",risk:"MEDIUM" as const,icon:Zap},
 {id:"C",name:"Provider C",provider:"Verified partner rail",cost:"₹930",settlement:"30 min",reliability:"97%",risk:"LOW" as const,icon:ShieldCheck,recommended:true},
];
export function RouteIntelligencePage(){const [selected,setSelected]=useState("C");return <AppShell title="Route Intelligence" eyebrow="Payments / PAY-1048"><PageIntro title="Route Intelligence" description="Compare available payment routes before execution." action={<span className="hidden text-xs text-muted-foreground sm:block">Updated just now</span>}/><div className="grid gap-4 lg:grid-cols-3">{routes.map(r=>{const Icon=r.icon;return <button onClick={()=>setSelected(r.id)} key={r.id} className={cn("relative text-left",selected===r.id&&"route-selected")}><Panel className={cn("h-full p-5 transition-all hover:border-primary/35",selected===r.id&&"border-primary/50 bg-primary/[.035]")}>{r.recommended&&<span className="absolute right-4 top-4 text-[9px] font-semibold uppercase tracking-widest text-primary">Recommended</span>}<span className="grid size-9 place-items-center rounded-md bg-secondary text-muted-foreground"><Icon className="size-4"/></span><p className="mt-5 text-[10px] uppercase tracking-widest text-muted-foreground">Route {r.id}</p><h3 className="mt-1 font-semibold">{r.name}</h3><p className="mt-1 text-xs text-muted-foreground">{r.provider}</p><div className="mt-6 grid grid-cols-2 gap-4 border-t border-border pt-4"><RouteMetric l="Cost" v={r.cost}/><RouteMetric l="Settlement" v={r.settlement}/><RouteMetric l="Reliability" v={r.reliability}/><div><p className="text-[10px] text-muted-foreground">Assessed Risk</p><div className="mt-1"><RiskBadge risk={r.risk}/></div></div></div></Panel></button>})}</div>
 <Panel className="mt-5 overflow-hidden border-primary/25"><div className="grid lg:grid-cols-[minmax(0,1fr)_auto]"><div className="p-6 sm:p-7"><div className="flex items-center gap-2 text-[10px] font-semibold uppercase tracking-[.15em] text-primary"><Sparkles className="size-4"/>FinSight recommends</div><h3 className="mt-3 text-2xl font-semibold">Route C <span className="text-base font-normal text-muted-foreground">· Provider C</span></h3><div className="mt-5 grid gap-3 text-sm sm:grid-cols-2">{["Lower assessed risk","High reliability","Faster settlement","Balanced total cost"].map(x=><span key={x} className="flex gap-2"><Check className="mt-0.5 size-4 text-risk-low"/>{x}</span>)}</div></div><div className="flex min-w-60 items-center border-t border-border bg-primary/[.035] p-6 lg:border-l lg:border-t-0"><Button className="w-full" asChild><Link to="/payment-confirmation">Select Route C<ArrowRight/></Link></Button></div></div></Panel>
 <Panel className="mt-5"><SectionHead title="Compare Routes" detail="Detailed cost, speed, and risk analysis"/><div className="overflow-x-auto"><table className="w-full min-w-[700px] text-sm"><thead className="border-b border-border text-left text-[10px] uppercase tracking-widest text-muted-foreground"><tr><th className="px-5 py-3">Metric</th>{routes.map(r=><th key={r.id} className="px-5 py-3">Route {r.id}</th>)}</tr></thead><tbody>{[["Provider","Bank Transfer","Provider B","Provider C"],["Total cost","₹1,420","₹680","₹930"],["Settlement","2–3 days","10 min","30 min"],["Reliability","94%","91%","97%"],["Risk","LOW","MEDIUM","LOW"]].map(row=><tr key={row[0]} className="border-b border-border last:border-0"><td className="px-5 py-3 text-muted-foreground">{row[0]}</td>{row.slice(1).map((v,i)=><td key={i} className={cn("px-5 py-3 font-medium",i===2&&"bg-primary/[.025] text-primary")}>{v}</td>)}</tr>)}</tbody></table></div></Panel></AppShell>}
function RouteMetric({l,v}:{l:string;v:string}){return <div><p className="text-[10px] text-muted-foreground">{l}</p><p className="mt-1 text-sm font-medium tabular-nums">{v}</p></div>}

export function ConfirmationPage(){const [checked,setChecked]=useState(false);return <AppShell title="Review Payment" eyebrow="Payments / PAY-1048"><PageIntro title="Review Payment" description="Confirm the details before simulating this transaction." action={<DemoLabel/>}/><div className="mx-auto max-w-3xl space-y-5"><Panel><SectionHead title="Payment Summary" detail="Final review before execution"/><div className="grid gap-px bg-border sm:grid-cols-2">{[["Vendor","ABC Software LLC"],["Amount","$18,700 USD"],["Route","Provider C"],["Risk","HIGH — Reviewed"],["Estimated Settlement","~30 minutes"],["Estimated Cost","₹930"]].map(([l,v])=><div key={l} className="bg-card p-5"><p className="text-xs text-muted-foreground">{l}</p><p className={cn("mt-1.5 text-sm font-medium",l==="Risk"&&"text-risk-high")}>{v}</p></div>)}</div></Panel><div className="rounded-lg border border-risk-high/25 bg-risk-high/5 p-5"><div className="flex gap-3"><AlertTriangle className="size-5 shrink-0 text-risk-high"/><div><h3 className="text-sm font-medium">This payment was flagged for review.</h3><p className="mt-1 text-xs leading-5 text-muted-foreground">Confirm that vendor details and the new destination account have been independently verified.</p></div></div></div><Panel className="p-5"><label className="flex cursor-pointer items-start gap-3"><Checkbox checked={checked} onCheckedChange={(v)=>setChecked(v===true)} className="mt-0.5"/><span className="text-sm">I have reviewed the payment details and verified the vendor information.</span></label><Button className="mt-5 w-full" size="lg" disabled={!checked} asChild={checked}>{checked?<Link to="/monitoring"><DemoLabel/> Simulate Payment<ArrowRight/></Link>:<span><DemoLabel/> Simulate Payment</span>}</Button><p className="mt-3 text-center text-[10px] text-muted-foreground">No funds will move. This action is for demonstration only.</p></Panel></div></AppShell>}

const timeline=[{l:"Payment Created",t:"14:22:04",done:true},{l:"Risk Analysis Completed",t:"14:22:07",done:true},{l:"Route Selected",t:"14:24:31",done:true},{l:"Payment Initiated",t:"14:25:02",done:true},{l:"Processing",t:"In progress",active:true},{l:"Settlement",t:"Est. 14:55",done:false}];
export function MonitoringPage(){const [progress,setProgress]=useState(4);useEffect(()=>{const t=setTimeout(()=>setProgress(5),5000);return()=>clearTimeout(t)},[]);return <AppShell title="Payment Monitor" eyebrow="Payments / TXN-FS-10482"><PageIntro title="Payment Monitor" description="Live status and transaction activity." action={<DemoLabel/>}/><div className="grid gap-5 xl:grid-cols-[minmax(0,1.2fr)_minmax(330px,.8fr)]"><Panel><SectionHead title="Transaction Progress" detail="TXN-FS-10482" action={<StatusBadge status={progress===5?"Completed":"Processing"}/>}/><div className="p-6 sm:p-8"><div className="space-y-0">{timeline.map((s,i)=>{const done=i<=progress;const active=i===progress;return <div key={s.l} className="grid grid-cols-[24px_minmax(0,1fr)_auto] gap-3"><div className="flex flex-col items-center"><span className={cn("grid size-6 place-items-center rounded-full border",done?"border-primary bg-primary text-primary-foreground":"border-border bg-card text-muted-foreground",active&&"animate-pulse")}>{done?<Check className="size-3.5"/>:<Circle className="size-2"/>}</span>{i<timeline.length-1&&<span className={cn("h-12 w-px",i<progress?"bg-primary":"bg-border")}/>}</div><span className={cn("pt-0.5 text-sm",!done&&"text-muted-foreground")}>{s.l}</span><span className="pt-0.5 text-xs text-muted-foreground">{active&&progress<5?"In progress":done?s.t:s.t}</span></div>})}</div></div></Panel><div className="space-y-5"><Panel><SectionHead title="Transaction Details"/><div className="divide-y divide-border px-5">{[["Transaction ID","TXN-FS-10482"],["Amount","$18,700 USD"],["Route","Provider C"],["Status",progress===5?"COMPLETED":"PROCESSING"],["Estimated settlement",progress===5?"Completed":"~30 minutes"]].map(([l,v])=><div key={l} className="flex justify-between gap-4 py-3 text-sm"><span className="text-muted-foreground">{l}</span><span className="font-mono text-right">{v}</span></div>)}</div></Panel><Panel><SectionHead title="Activity" detail="Verified transaction events"/><div className="p-5"><div className="flex gap-3"><span className="mt-1 size-2 rounded-full bg-primary"/><div><p className="text-sm">Payment submitted to Provider C</p><p className="mt-1 text-xs text-muted-foreground">14:25:02 · Secure connection verified</p></div></div></div></Panel></div></div></AppShell>}
