/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as HelpRouteImport } from './routes/help'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as MonitoringRouteImport } from './routes/monitoring'
import { Route as NewPaymentRouteImport } from './routes/new-payment'
import { Route as PaymentConfirmationRouteImport } from './routes/payment-confirmation'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RiskCenterRouteImport } from './routes/risk-center'
import { Route as RiskReviewRouteImport } from './routes/risk-review'
import { Route as RouteIntelligenceRouteImport } from './routes/route-intelligence'
import { Route as SettingsRouteImport } from './routes/settings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitoringRoute = MonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => rootRouteImport,
} as any)
const NewPaymentRoute = NewPaymentRouteImport.update({
  id: '/new-payment',
  path: '/new-payment',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentConfirmationRoute = PaymentConfirmationRouteImport.update({
  id: '/payment-confirmation',
  path: '/payment-confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RiskCenterRoute = RiskCenterRouteImport.update({
  id: '/risk-center',
  path: '/risk-center',
  getParentRoute: () => rootRouteImport,
} as any)
const RiskReviewRoute = RiskReviewRouteImport.update({
  id: '/risk-review',
  path: '/risk-review',
  getParentRoute: () => rootRouteImport,
} as any)
const RouteIntelligenceRoute = RouteIntelligenceRouteImport.update({
  id: '/route-intelligence',
  path: '/route-intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/help': typeof HelpRoute
  '/insights': typeof InsightsRoute
  '/monitoring': typeof MonitoringRoute
  '/new-payment': typeof NewPaymentRoute
  '/payment-confirmation': typeof PaymentConfirmationRoute
  '/payments': typeof PaymentsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/risk-center': typeof RiskCenterRoute
  '/risk-review': typeof RiskReviewRoute
  '/route-intelligence': typeof RouteIntelligenceRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/help': typeof HelpRoute
  '/insights': typeof InsightsRoute
  '/monitoring': typeof MonitoringRoute
  '/new-payment': typeof NewPaymentRoute
  '/payment-confirmation': typeof PaymentConfirmationRoute
  '/payments': typeof PaymentsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/risk-center': typeof RiskCenterRoute
  '/risk-review': typeof RiskReviewRoute
  '/route-intelligence': typeof RouteIntelligenceRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/help': typeof HelpRoute
  '/insights': typeof InsightsRoute
  '/monitoring': typeof MonitoringRoute
  '/new-payment': typeof NewPaymentRoute
  '/payment-confirmation': typeof PaymentConfirmationRoute
  '/payments': typeof PaymentsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/risk-center': typeof RiskCenterRoute
  '/risk-review': typeof RiskReviewRoute
  '/route-intelligence': typeof RouteIntelligenceRoute
  '/settings': typeof SettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/help'
    | '/insights'
    | '/monitoring'
    | '/new-payment'
    | '/payment-confirmation'
    | '/payments'
    | '/reset-password'
    | '/risk-center'
    | '/risk-review'
    | '/route-intelligence'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/help'
    | '/insights'
    | '/monitoring'
    | '/new-payment'
    | '/payment-confirmation'
    | '/payments'
    | '/reset-password'
    | '/risk-center'
    | '/risk-review'
    | '/route-intelligence'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/help'
    | '/insights'
    | '/monitoring'
    | '/new-payment'
    | '/payment-confirmation'
    | '/payments'
    | '/reset-password'
    | '/risk-center'
    | '/risk-review'
    | '/route-intelligence'
    | '/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  HelpRoute: typeof HelpRoute
  InsightsRoute: typeof InsightsRoute
  MonitoringRoute: typeof MonitoringRoute
  NewPaymentRoute: typeof NewPaymentRoute
  PaymentConfirmationRoute: typeof PaymentConfirmationRoute
  PaymentsRoute: typeof PaymentsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RiskCenterRoute: typeof RiskCenterRoute
  RiskReviewRoute: typeof RiskReviewRoute
  RouteIntelligenceRoute: typeof RouteIntelligenceRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitoring': {
      id: '/monitoring'
      path: '/monitoring'
      fullPath: '/monitoring'
      preLoaderRoute: typeof MonitoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-payment': {
      id: '/new-payment'
      path: '/new-payment'
      fullPath: '/new-payment'
      preLoaderRoute: typeof NewPaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-confirmation': {
      id: '/payment-confirmation'
      path: '/payment-confirmation'
      fullPath: '/payment-confirmation'
      preLoaderRoute: typeof PaymentConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risk-center': {
      id: '/risk-center'
      path: '/risk-center'
      fullPath: '/risk-center'
      preLoaderRoute: typeof RiskCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risk-review': {
      id: '/risk-review'
      path: '/risk-review'
      fullPath: '/risk-review'
      preLoaderRoute: typeof RiskReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/route-intelligence': {
      id: '/route-intelligence'
      path: '/route-intelligence'
      fullPath: '/route-intelligence'
      preLoaderRoute: typeof RouteIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  HelpRoute: HelpRoute,
  InsightsRoute: InsightsRoute,
  MonitoringRoute: MonitoringRoute,
  NewPaymentRoute: NewPaymentRoute,
  PaymentConfirmationRoute: PaymentConfirmationRoute,
  PaymentsRoute: PaymentsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RiskCenterRoute: RiskCenterRoute,
  RiskReviewRoute: RiskReviewRoute,
  RouteIntelligenceRoute: RouteIntelligenceRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
